// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Stream struct {
	ID      string
	AdminID uuid.NullUUID
	Started sql.NullBool
	Ended   sql.NullBool
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
}
